PLAY_TEXT = "Включить поток"
STOP_TEXT = "Остановить поток"
CONNECTION_AWATING = "Ожидание сервера..."
CONNECTED_TO = "Подключено к"
RESTART_SERVER = "Перезапустить сервер?"
ROI_BRIGHTNESS_LABEL = "Яркость:"
ROI_CONTRAST_LABEL = "Контрастность:"